#!/bin/bash

$install_dir="~/.duckduckgoog"

echo "Cloning git repo..."
git clone https://github.com/evanrelf/duckduckgoog.git $install_dir

cd $install_dir

echo "Installing Node modules..."
npm install

echo "Installing LaunchAgent..."
rm -f ~/Library/LaunchAgents/local.duckduckgoog.plist
sed "s REPLACEME $install_dir " < LaunchAgent.plist > ~/Library/LaunchAgents/local.duckduckgoog.plist

echo "Starting LaunchAgent..."
launchctl load ~/Library/LaunchAgents/local.duckduckgoog.plist
launchctl start local.duckduckgoog.plist

echo "Install complete"
